In [1]:
import numpy as np

In [4]:
# Create array using numpy 
# Creating 1D array 

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)       #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [10]:
# 2D array 
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

print('Array: \n', arr)
print('Shape: ', arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size: ",arr.size)
print("Data type", arr.dtype)
print("Item size(bytes): ",arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size:  6
Data type int64
Item size(bytes):  8


In [24]:
# Vector Operation 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ",arr1+arr2)
print("Subtraction: ",arr1-arr2)
print("Multiplication: ",arr1*arr2)
print("Division: ",arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [25]:
arr = np.array([2,3,4,5,6])

# Square root 
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

# Sine 
print(np.sin(arr))

# log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
# Array slicing and indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [32]:
print(arr[0][0])

1


In [42]:
# to pick up 7,8,11,12
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [49]:
# to pick up 1,2,5,6 
arr[:2,:2]

array([[1, 2],
       [5, 6]])

In [52]:
# pick up 3,4,7,8
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [57]:
# Pick up 6,7,10,11
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [59]:
# Modify array elements 
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [62]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [65]:
# Normalization 
# To have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,5,6])

mean = np.mean(data)
std_dev = np.std(data)
print(mean)
print(std_dev)

# Normalize the data 
normalized_data = (data - mean) / std_dev
print("Normalized data: ",normalized_data)

3.4
1.854723699099141
Normalized data:  [-1.29399328 -0.75482941 -0.21566555  0.86266219  1.40182605]


In [67]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean 
print('Mean: ',np.mean(data))

# median 
print("Median: ",np.median(data))

# standard deviation 
print("Standard Deviation: ",np.std(data))

# variance
print('Variance', np.var(data))

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance 8.25


In [68]:
# Logical operation 
data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
data[(data >=5) & (data<=8)]

array([5, 6, 7, 8])